[project]
name = "flaskproject"
version = "0.1.0"
description = "flask project"
requires-python = ">=3.13"
dependencies = [
    "flask==3.1.1",
    "flask-login>=0.6.3",
    "python-dotenv==1.1.0",
]
